services:
  - type: web
    name: medical-officer-quiz-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_ID
        value: "-1003904563319"
